name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: git config user.name "Yuliya Zhukova"
    - run: git config user.email "zhkv.jl@gmail.com"

    - run: npm install
    - run: npm run deploy
